Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing
$ErrorActionPreference='Stop'
$RepoOwner='minhaversao'; $RepoName='bolado'; $ReleaseTag='rap-talis-media'; $GraphVersion='v24.0'
$AppDir=Join-Path $env:APPDATA 'RapTalisPublisher'; New-Item -ItemType Directory -Force -Path $AppDir|Out-Null
$ConfigPath=Join-Path $AppDir 'config.json'; $LogPath=Join-Path $AppDir 'publisher.log'
function Log($m){Add-Content $LogPath "$(Get-Date -Format s) $m" -Encoding UTF8}
function Protect($s){if(!$s){return ''};ConvertFrom-SecureString (ConvertTo-SecureString $s -AsPlainText -Force)}
function Unprotect($s){if(!$s){return ''};$x=ConvertTo-SecureString $s;$p=[Runtime.InteropServices.Marshal]::SecureStringToBSTR($x);try{[Runtime.InteropServices.Marshal]::PtrToStringBSTR($p)}finally{[Runtime.InteropServices.Marshal]::ZeroFreeBSTR($p)}}
function LoadCfg(){if(!(Test-Path $ConfigPath)){return [pscustomobject]@{githubToken='';metaToken='';igUserId='';shareToFeed=$true}};$r=Get-Content $ConfigPath -Raw|ConvertFrom-Json;[pscustomobject]@{githubToken=(Unprotect $r.githubToken);metaToken=(Unprotect $r.metaToken);igUserId=$r.igUserId;shareToFeed=[bool]$r.shareToFeed}}
function SaveCfg($g,$m,$i,$s){@{githubToken=(Protect $g);metaToken=(Protect $m);igUserId=$i;shareToFeed=$s}|ConvertTo-Json|Set-Content $ConfigPath -Encoding UTF8}
function GHHeaders($t){@{Authorization="Bearer $t";Accept='application/vnd.github+json';'X-GitHub-Api-Version'='2022-11-28';'User-Agent'='RapTalisPublisher'}}
function GetRelease($t){$h=GHHeaders $t;$u="https://api.github.com/repos/$RepoOwner/$RepoName/releases/tags/$ReleaseTag";try{return Invoke-RestMethod $u -Headers $h}catch{if($_.Exception.Response.StatusCode.value__ -ne 404){throw}};$b=@{tag_name=$ReleaseTag;target_commitish='main';name='Rap Talis Media Bridge';body='Assets temporarios da automacao';draft=$false;prerelease=$false}|ConvertTo-Json;Invoke-RestMethod "https://api.github.com/repos/$RepoOwner/$RepoName/releases" -Headers $h -Method Post -Body $b -ContentType 'application/json'}
function UploadAsset($t,$p){$r=GetRelease $t;$n="$(Get-Date -Format yyyyMMdd-HHmmss)-$([guid]::NewGuid().ToString('N').Substring(0,8))-$([IO.Path]::GetFileName($p))" -replace '[^A-Za-z0-9._-]','_';$base=$r.upload_url -replace '\{\?name,label\}$','';$u="$base?name=$([uri]::EscapeDataString($n))";Invoke-RestMethod $u -Headers (GHHeaders $t) -Method Post -InFile $p -ContentType 'video/mp4'}
function DeleteAsset($t,$id){Invoke-RestMethod "https://api.github.com/repos/$RepoOwner/$RepoName/releases/assets/$id" -Headers (GHHeaders $t) -Method Delete|Out-Null}
function WaitUrl($u){for($i=0;$i -lt 60;$i++){try{$r=Invoke-WebRequest $u -Method Head -UseBasicParsing -MaximumRedirection 8 -TimeoutSec 15;if($r.StatusCode -ge 200 -and $r.StatusCode -lt 400){return $true}}catch{};Start-Sleep 2};$false}
function CreateContainer($t,$ig,$url,$cap,$feed){Invoke-RestMethod "https://graph.facebook.com/$GraphVersion/$ig/media" -Method Post -Body @{media_type='REELS';video_url=$url;caption=$cap;share_to_feed=($(if($feed){'true'}else{'false'}));access_token=$t}}
function WaitContainer($t,$id){for($i=0;$i -lt 96;$i++){$u="https://graph.facebook.com/$GraphVersion/$id?fields=status_code,status&access_token=$([uri]::EscapeDataString($t))";$s=Invoke-RestMethod $u;if($s.status_code -eq 'FINISHED'){return};if($s.status_code -in @('ERROR','EXPIRED')){throw "Meta: $($s.status_code) $($s.status)"};Start-Sleep 5};throw 'Tempo esgotado aguardando a Meta.'}
function PublishContainer($t,$ig,$id){Invoke-RestMethod "https://graph.facebook.com/$GraphVersion/$ig/media_publish" -Method Post -Body @{creation_id=$id;access_token=$t}}
function ValidateVideo($p){if(!(Test-Path $p)){throw 'Arquivo nao encontrado'};$e=[IO.Path]::GetExtension($p).ToLower();if($e -notin @('.mp4','.mov','.m4v')){throw 'Formato invalido'};if((Get-Item $p).Length -le 0){throw 'Arquivo vazio'}}
$form=New-Object Windows.Forms.Form;$form.Text='Rap Talis Publisher - GitHub Bridge';$form.Size=New-Object Drawing.Size(1180,760);$form.StartPosition='CenterScreen'
$h=New-Object Windows.Forms.Label;$h.Text='RAP TALIS - PUBLICACAO EM LOTE';$h.Font=New-Object Drawing.Font('Segoe UI',16,[Drawing.FontStyle]::Bold);$h.AutoSize=$true;$h.Location='20,15';$form.Controls.Add($h)
$s=New-Object Windows.Forms.Label;$s.Text='GitHub Releases -> Meta -> Reel publicado -> limpeza automatica';$s.AutoSize=$true;$s.Location='22,48';$form.Controls.Add($s)
function Btn($text,$x,$w){$b=New-Object Windows.Forms.Button;$b.Text=$text;$b.Location="$x,82";$b.Size="$w,36";$form.Controls.Add($b);$b}
$add=Btn 'Adicionar videos' 20 140;$csv=Btn 'Importar CSV' 170 120;$rem=Btn 'Remover selecionado' 300 155;$pub=Btn 'PUBLICAR FILA' 965 170;$pub.Anchor='Top,Right'
$cfgBtn=New-Object Windows.Forms.Button;$cfgBtn.Text='Configuracoes';$cfgBtn.Location='1015,16';$cfgBtn.Size='120,34';$cfgBtn.Anchor='Top,Right';$form.Controls.Add($cfgBtn)
$grid=New-Object Windows.Forms.DataGridView;$grid.Location='20,132';$grid.Size='1115,500';$grid.Anchor='Top,Bottom,Left,Right';$grid.AllowUserToAddRows=$false;$grid.RowHeadersVisible=$false;$grid.SelectionMode='FullRowSelect';$grid.MultiSelect=$true;$form.Controls.Add($grid)
$c=New-Object Windows.Forms.DataGridViewTextBoxColumn;$c.Name='Arquivo';$c.HeaderText='Arquivo';$c.ReadOnly=$true;$c.Width=260;$grid.Columns.Add($c)|Out-Null
$c=New-Object Windows.Forms.DataGridViewTextBoxColumn;$c.Name='Caminho';$c.Visible=$false;$grid.Columns.Add($c)|Out-Null
$c=New-Object Windows.Forms.DataGridViewTextBoxColumn;$c.Name='Legenda';$c.HeaderText='Legenda';$c.AutoSizeMode='Fill';$c.DefaultCellStyle.WrapMode='True';$grid.Columns.Add($c)|Out-Null
$c=New-Object Windows.Forms.DataGridViewTextBoxColumn;$c.Name='Status';$c.HeaderText='Status';$c.ReadOnly=$true;$c.Width=190;$grid.Columns.Add($c)|Out-Null
$status=New-Object Windows.Forms.Label;$status.Text='Pronto.';$status.Location='20,650';$status.Size='1115,30';$status.Anchor='Bottom,Left,Right';$form.Controls.Add($status)
function SetStatus($r,$v){$r.Cells['Status'].Value=$v;[Windows.Forms.Application]::DoEvents()}
$add.Add_Click({$d=New-Object Windows.Forms.OpenFileDialog;$d.Multiselect=$true;$d.Filter='Videos|*.mp4;*.mov;*.m4v';if($d.ShowDialog() -eq 'OK'){foreach($f in $d.FileNames){$dup=$false;foreach($r in $grid.Rows){if($r.Cells['Caminho'].Value -eq $f){$dup=$true}};if(!$dup){$i=$grid.Rows.Add();$r=$grid.Rows[$i];$r.Cells['Arquivo'].Value=[IO.Path]::GetFileName($f);$r.Cells['Caminho'].Value=$f;$r.Cells['Status'].Value='Na fila'}};$status.Text="$($grid.Rows.Count) video(s) na fila."}})
$csv.Add_Click({$d=New-Object Windows.Forms.OpenFileDialog;$d.Filter='CSV|*.csv';if($d.ShowDialog() -eq 'OK'){foreach($x in (Import-Csv $d.FileName)){foreach($r in $grid.Rows){if($r.Cells['Arquivo'].Value -eq $x.arquivo){$r.Cells['Legenda'].Value=$x.legenda}}}}})
$rem.Add_Click({@($grid.SelectedRows)|Sort-Object Index -Descending|ForEach-Object{$grid.Rows.RemoveAt($_.Index)}})
$cfgBtn.Add_Click({$old=LoadCfg;$f=New-Object Windows.Forms.Form;$f.Text='Configuracoes';$f.Size='620,390';$f.StartPosition='CenterParent';$labels=@('GitHub token','Meta access token','Instagram User ID');$ys=@(30,100,170);$boxes=@();for($i=0;$i -lt 3;$i++){$l=New-Object Windows.Forms.Label;$l.Text=$labels[$i];$l.Location="20,$($ys[$i])";$l.AutoSize=$true;$f.Controls.Add($l);$t=New-Object Windows.Forms.TextBox;$t.Location="20,$($ys[$i]+24)";$t.Size='560,28';$f.Controls.Add($t);$boxes+=$t};$boxes[0].UseSystemPasswordChar=$true;$boxes[1].UseSystemPasswordChar=$true;$boxes[0].Text=$old.githubToken;$boxes[1].Text=$old.metaToken;$boxes[2].Text=$old.igUserId;$ch=New-Object Windows.Forms.CheckBox;$ch.Text='Compartilhar tambem no feed';$ch.Location='20,245';$ch.AutoSize=$true;$ch.Checked=$old.shareToFeed;$f.Controls.Add($ch);$b=New-Object Windows.Forms.Button;$b.Text='Salvar';$b.Location='470,315';$b.Size='110,30';$f.Controls.Add($b);$b.Add_Click({SaveCfg $boxes[0].Text $boxes[1].Text $boxes[2].Text $ch.Checked;$f.Close()});[void]$f.ShowDialog($form)})
$pub.Add_Click({if($grid.Rows.Count -eq 0){[Windows.Forms.MessageBox]::Show('Adicione videos primeiro.')|Out-Null;return};$x=LoadCfg;if(!$x.githubToken -or !$x.metaToken -or !$x.igUserId){[Windows.Forms.MessageBox]::Show('Preencha as Configuracoes primeiro.')|Out-Null;return};$pub.Enabled=$false;try{$n=0;foreach($r in $grid.Rows){$n++;$asset=$null;try{$p=[string]$r.Cells['Caminho'].Value;$cap=[string]$r.Cells['Legenda'].Value;SetStatus $r 'Validando';ValidateVideo $p;SetStatus $r 'Hospedando no GitHub';$asset=UploadAsset $x.githubToken $p;Log "asset $($asset.id) $($asset.browser_download_url)";SetStatus $r 'Testando URL';if(!(WaitUrl $asset.browser_download_url)){throw 'URL publica indisponivel'};SetStatus $r 'Meta processando';$cont=CreateContainer $x.metaToken $x.igUserId $asset.browser_download_url $cap $x.shareToFeed;WaitContainer $x.metaToken $cont.id;SetStatus $r 'Publicando';$done=PublishContainer $x.metaToken $x.igUserId $cont.id;if(!$done.id){throw 'Meta nao confirmou a publicacao'};SetStatus $r "Publicado $($done.id)";try{DeleteAsset $x.githubToken $asset.id}catch{Log "falha limpando asset $($asset.id): $($_.Exception.Message)"}}catch{SetStatus $r "Falhou: $($_.Exception.Message)";Log "falha: $($_.Exception.Message)"}};$status.Text='Fila concluida.'}finally{$pub.Enabled=$true}})
[void]$form.ShowDialog()
